### ISSUE TITLE
splice event  is drawn over all tracks sometimes

### ISSUE THREAD

**Issue by malewins** [malewins/SEQing#61]
This happens sometimes without any obvious pattern.
![grafik](https://user-images.githubusercontent.com/29062188/64690504-df679f00-d490-11e9-8080-19785162586b.png)
When the display mode is switched to score based, it's gone:
![grafik](https://user-images.githubusercontent.com/29062188/64690578-0b832000-d491-11e9-844a-951748608694.png)

This was: AT1G04640

**Comment by YBramkamp** [comment]
The issue was related to a trace with a single row of splice events being treated as not having events at all, thus setting the height of the corresponding y-axis to 0 and causing the phenomenon. Score based display was unaffected due to it having its own code that didn't have the new modification yet. With the incoming fix all three display types should work correctly and still zero unneeded rows.
